server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/OverLook-View/springcloud-study/
          search-paths: config
          username:
          password:
